### ISSUE TITLE
Cannot create new workspace (different error this time)

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#91] opened 2021-02-01 16:03 UTC
This is a follow up to #88. Seems like it's still not possible to create workspaces through MC.

When trying to create a new workspace, I am getting a new error:
`{"message":"cz.cvut.kbss.jopa.oom.exceptions.UnpersistedChangeException: The following instances were neither persisted nor marked as cascade for persist: [User{Karel Klíma, username='karelklima@gmail.com'}]","requestUri":"/sgov-server/workspaces"}`

As far as I can tell I didn't change anything in MC that should affect this.

**Comment by psiotwo** [comment] 2021-02-01 17:08
Cannot reproduce on https://mission-control.netlify.app/ logged as Petr Kremen. Will check server logs.

**Comment by psiotwo** [comment] 2021-02-01 20:58
The user management logic will be a follows:
1) Keycloak will be responsible for user creation/update being synchronized to GraphDB - still not resolved, see https://trello.com/c/eUd6Kc4D/316-integrovat-graphdb-a-keycloak
2) Client applications rely on users being in GraphDB

Until 1) is resolved only existing users shall be allowed to create/update workspaces.

**Comment by psiotwo** [comment] 2021-02-01 21:04
Please @karelklima try to create a workspace using your account now (in the meantime @ledsoft synchronized existing accounts to GraphDB manually).

If the problem when logged as karelklima@gmail.com is gone, feel free to close this ticket.

**Comment by karelklima** [comment] 2021-02-01 23:48
I still cannot create a workspace, the same error is still in place. I tried to log out but it didn't help. So it seems like the account sync didn't help, OR there is a typo in my email address somewhere.

**Comment by ledsoft** [comment] 2021-02-02 07:08
Agree with @karelklima , I cannot create a workspace either. Will investigate SGoV source code.

**Comment by psiotwo** [comment] 2021-02-02 08:48
Fixed, please test @karelklima @ledsoft

**Comment by ledsoft** [comment] 2021-02-02 08:55
Works for me.

**Closed** 2021-02-02 18:33 UTC
Labels: bug
