### ISSUE TITLE
Workspaces endpoints returns different last modified date from the single workspace endpoint.

### ISSUE THREAD

**Issue by karelklima** [opendata-mvcr/sgov#72] opened 2020-09-23 16:46 UTC
Case

- workspace: https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1759811010
- lastModified according to the /workspaces endpoint: **1600860010129**
- lastModified according to /workspaces/instance-1759811010: **1600184670064**

**Comment by psiotwo** [comment] 2020-09-23 19:48
Cannot find the referenced workspace. Tried two other workspaces instance1170301076 and instance69809529, and for them both endpoints return the same time.

Feel free to reopen with a reference to a problematic workspace.

**Comment by karelklima** [comment] 2020-09-23 19:52
This is another example: https://mission-control.netlify.app/workspaces/instance-662374584
lastModified in workspaces: 1600507752395
lastModified in detail: 1599724074335

**Comment by psiotwo** [comment] 2020-09-23 20:08
Can see it - funny thing is that I cannot reproduce it when running locally :facepalm:, just on the KBSS server. Going to take a look, maybe some localization setup ...

**Comment by psiotwo** [comment] 2020-09-24 21:55
@karelklima should be resolved. Checked on some workspaces. Please test.

**Comment by psiotwo** [comment] 2020-10-05 18:27
Closing. Please reopen in case the problem is back.

**Closed by psiotwo** 2020-10-05 18:27 UTC
Labels: bug
